// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Atcommands
 * Place the definition of custom atcommands in this file.
 * Format:
 *	ACMD_DEF(command_name),
 **/

//ACMD_DEF(newcommand),
ACMD_DEF(arealoot),
ACMD_DEF(profession),
ACMD_DEF(hints),
ACMD_DEF(pvpscore),
ACMD_DEF(resinfo),
ACMD_DEF(title),
ACMD_DEF(whosell),
ACMD_DEF(whobuy),
